name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:
  build:
    strategy:
      matrix:
        config:
          - {name: "Linux", os: ubuntu-latest}
          - {name: "LinuxClang", os: ubuntu-latest}
          - {name: "Windows", os: windows-latest}

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Requirements (Linux)
      if: startsWith(matrix.config.name, 'Linux')
      run: sudo apt-get install libx11-dev mesa-common-dev libglu1-mesa-dev libxrender-dev libxfixes-dev libglew-dev libxext-dev

    - name: Requirements (LinuxClang)
      if: matrix.config.name == 'LinuxClang'
      run: sudo apt-get install clang && echo "CC=/usr/bin/clang" >> $GITHUB_ENV && echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV

    - name: Configure
      run: mkdir build && cd build && cmake ..

    - name: Build
      run: cd build && cmake --build .

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    - name: Test
      run: cd bin64 && ./hl_test
